### ISSUE TITLE
Fatal error: Call to undefined function db_user_create() dans install.php

### ISSUE THREAD

**Issue by zefredz** [ulbpodcast/ezcast#3]
J'ai l'erreur suivante lors de l'installation de ezcast sur ma machine :

Fatal error: Call to undefined function db_user_create() in /usr/local/ezcast/ezadmin/web_install.php on line 545

**Comment by awijns** [comment]
Bonjour Frédéric,

Il me semble que c’est une erreur due à la dernière refactorisation du code. 
Précédemment, les fonctions de création et gestion des utilisateurs se trouvaient dans lib_database.php qui est inclue dans ezadmin/web_install.php mais lors de la dernière refactorisation du code, on n’a pas mis l’installeur à jour. 
Pour résoudre cela, il faut inclure ezadmin/lib_sql_management.php dans ezadmin/web_install.php mais du coup, ca entraine d’autres conflits.

J’ai prévu un correctif pour cela. Il sera mis en ligne dans le courant de la semaine prochaine, avec plusieurs autres corrections majeures.

Bonne aprem',
Arnaud

**Comment by awijns** [comment]
Bonjour Frédéric,

Il me semble que c’est une erreur due à la dernière refactorisation du code. 
Précédemment, les fonctions de création et gestion des utilisateurs se trouvaient dans lib_database.php qui est inclue dans ezadmin/web_install.php mais lors de la dernière refactorisation du code, on n’a pas mis l’installeur à jour. 
Pour résoudre cela, il faut inclure ezadmin/lib_sql_management.php dans ezadmin/web_install.php mais du coup, ca entraine d’autres conflits.

J’ai prévu un correctif pour cela. Il sera mis en ligne dans le courant de la semaine prochaine, avec plusieurs autres corrections majeures.

Bonne aprem',
Arnaud

Arnaud WIJNS
ULB Podcast | Informaticien
http://podcast.ulb.ac.be <http://podcast.ulb.ac.be/>

Téléphone : 02/650.29.26
Email : arnaud.wijns@ulb.ac.be <mailto:arnaud.wijns@ulb.ac.be>

Université libre de Bruxelles
Campus du Solbosch - CP 160/26
Avenue F.D. Roosevelt, 50 - 1050 Ixelles

**Comment by zefredz** [comment]
OK, merci

Bonne fin de journée,

Frédéric

**Comment by awijns** [comment]
Bonjour,

La nouvelle version d'EZcast est maintenant disponible sur Github. Celle-ci devrait corriger le bug rencontré précédemment. 

Bonne journée,
Arnaud.

**Comment by zefredz** [comment]
Super, ça fonctionne.

Merci beaucoup et bonne journée,

Frédéric
